### ISSUE TITLE
문제집 가져오기 페이지를 확인해주세요

### ISSUE THREAD

**Issue by seunghee114** [team-quddy/Quddy-frontend#57]
문제집 가져오기 : `get  api/solver/exam/{id}`

해당 요청에서 응시한 결과가 있는 경우 아래와 같은 에러가 발생합니다.
```
TypeError: Cannot read properties of undefined (reading 'problems')
```

코드를 확인해보니 https://github.com/team-quddy/Quddy-frontend/blob/main/src/apis/Solver.ts 의 13번째 줄에서 처리가 되는 것 같긴 한데 혹시 배포된 서버에도 반영되었는지 궁금합니다.~

문제집 가져오기 요청의 response는 다음과 같습니다.

응시한 경우
```
{
  "id" : "응시결과 id"
}
```
응시하지 않은 경우
```
{
    "exam" :{
        "title" : "제목",
        "date" : "출제날짜",
        "problems" : [
            {
                "id" : "문제 PK",
                "question" : "문항",
                "exImg" : "보기",
                "exText" : "보기",
                "objective" : "문제 유형",
                "opt" : "선택지"
            }
        ]
    }
}
```

**Comment by Begachu** [comment]
수동배포인지라 최종버전을 배포버전에 반영하는 것을 잊었었네요...
업데이트하여 해결했습니다!
